### ISSUE TITLE
Thank you for this project

### ISSUE THREAD

**Issue by RamonSmit** [gduteil/OpenThermGateway#1]
Hi, 

First, thank you very much for creating this project. This worked out perfect for my situation. I'm really grateful that people like you are creating these cool projects for the open source community. 

 I saw in your readme "_Overrides don't work yet._". Is that something you're willing to create into the project? It would be a great nice to have in this project. 
 
 Again, thanks for this cool project. 
 
 - Ramon

**Comment by gduteil** [comment]
Hi, thank you for your message.

The overrides were something I originally wanted to add, but with the  OpenTherm protocol the settings are sent by the master (thermostat). 
I wanted to keep the my thermostat, and as it never request the boiler current values, I could do overrides but the thermostat settings were not consistent.

For my personal use, I made another integration which connects to the Atlantic Cozytouch cloud (the official integration was not using the same servers and API) to control the thermostat settings and forward them to the boiler, and as only few values are available in the cloud API and the refresh rate is very low, I'm using the gateway to retrieve all the values from the boiler.

Can you tell me more about the device you are using ? 
We can check if the limitation exists for you, and even if it does we can imagine trying different ways to override and see if you can find something acceptable.

**Comment by RamonSmit** [comment]
Hi, thanks for your quick response. 

I'm currently using a Toon thermostat. The issue I'm trying to solve is the usage with my Zigbee radiator thermostats. The thing I'd like to achieve is that every room has its own setpoint, that eventually has to be a trigger in Home Assistant to enable the boiler. Since Toon does not work with Zigbee, but with Z-Wave and given that the official API for the Toon is unstable, I'd like to create a local only solution. 

The radiator thermostats sends their data trough zigbee2mqtt to Home Assistant, and from my logic in Home Assistant I'd like to override the Toon settings (or totally circumvent Toon as a whole)  and send a _"demand temperature" _ to the boiler. 

Would something like that be achievable?

**Comment by gduteil** [comment]
The way OpenTherm works for "write" values (Master->Slave) is master writes a value and the slave acknowledges it by sending the applied value, there is a chance your thermostat uses the reply to set it's own value (this is not the case with the Navilink).

The ON/OFF works differently, it's in the status "read" request message, the master sets the flags in the 8 most significant bits in the 16 bits "read" requests, the slave fills the 8 least significant bits with it's own status.

Do you only want to override boiler activation or you also want override the temperature setpoint ?

**Comment by gduteil** [comment]
I'll try to find time this week-end to add a basic overrides to test, I'll let you know

**Comment by gduteil** [comment]
I just added an override for the temperature setpoint, as expected the thermostat (at least the Navilink) shows it's own value but the sensor value from the boiler shows it's overridden.

For now it's a basic number control, setting 0 will disable the override.

Simply add this to your configuration to add the control :

```yaml
number:
  - platform: openthermgw
    t_roomset_override:
      name: "Temperature Override"
```

**Comment by RamonSmit** [comment]
Woah, yes! 🔥 

![](https://media1.tenor.com/m/KR5oIxQgfEcAAAAd/yes-awesome.gif)
